### ISSUE TITLE
Add an option to make bprogress indeterminate

### ISSUE THREAD

**Issue by GowsikChandran** [Skyleen77/bprogress#133]
### Feature Description

Would you please add an option to make nprogress indeterminate.
I mean a progress bar that doesn't have 100% destination. It would be indicating loading of sth.

**Comment by Skyleen77** [comment]
Hello, good idea, I'll add that very soon!

**Comment by Skyleen77** [comment]
I've added this in version `1.3` of BProgress.
To use it, do : 
```ts
BProgress.configure({
  indeterminate: true,
});
```
If you encounter any problems or have any questions, don't hesitate!

**Comment by GowsikChandran** [comment]
@Skyleen77 
thank you for the Implementation.

How to control the speed of the indeterminate bar?

**Comment by Skyleen77** [comment]
@GowsikChandran 

Maybe you can modify that in CSS. 
The CSS file is here : https://bprogress.vercel.app/docs/style.

For exemple, you can play with the animation values by increasing the number of seconds to make the animation slower like this:
```css
.bprogress .indeterminate .inc {
  animation: bprogress-indeterminate-increase 3s infinite;
}
 
.bprogress .indeterminate .dec {
  animation: bprogress-indeterminate-decrease 3s 0.5s infinite;
}
```

Or you can also change the animation as you wish, the bprogress css is a base but is totally customizable.
